modLoader="javafml"
loaderVersion="[47,)"
license="MIT License https://github.com/McJtyMods/RFToolsBase/blob/1.16/LICENCE"
issueTrackerURL="http://github.com/McJtyMods/RFToolsBase/issues"
displayURL="http://github.com/McJtyMods/RFToolsBase/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[mods]]
modId="rftoolsbase"
version="${file.jarVersion}"
displayName="RFToolsBase"
#updateJSONURL="http://myurl.me/" #optional
description='''
The base class for all RFTools tech mods (and XNet/Deep Resonance)
'''
[[dependencies.rftoolsbase]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rftoolsbase]]
    modId="mcjtylib"
    mandatory=true
    versionRange="[1.20-8.0.4,)"
    ordering="AFTER"
    side="BOTH"